# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Headscale installation tasks
  block:
    - name: Validate Headscale configuration
      when: headscale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Headscale
      when: headscale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-headscale
    - install-all
    - install-headscale

- name: Perform Headscale uninstallation tasks
  block:
    - name: Uninstall Headscale
      when: not headscale_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-headscale
